name: PHPUnit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, dom, fileinfo, curl, intl, json, libxml, pdo, pdo_mysql, tokenizer, xml, zip
        coverage: xdebug
        tools: composer:v2
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer require --dev phpunit/phpunit:^9.5
    
    - name: Set up WordPress test environment
      run: |
        bash tests/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest true
    
    - name: Run PHPUnit
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --log-junit build/logs/junit.xml --coverage-clover build/logs/clover.xml
    
    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        file: build/logs/clover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
